db:
  url: "postgresql+psycopg2://webatlas:webatlas@postgres:5432/webatlas"

rate_limit:
  rps: 10

import:
  api_url_template: "https://api.2ip.io/cms/bitrix/ru?page={page}&token={token}"
  token: "o0pi7zyk6tp3bqmh"
  max_domains: 1000000
  file_path: "domains.txt"

audit:
  concurrency: 6                    # параллельность
  timeouts:
    total: 10                       # секунд, общий таймаут на запрос
