db:
  url: "postgresql+psycopg2://webatlas:webatlas@postgres:5432/webatlas"

rate_limit:
  rps: 1000

import:
  url_template: "https://purecrawl.com/domains/ru.txt.zip"

audit:
  concurrency: 1000                  # параллельность
  persist_concurrency: 200           # параллельная запись результатов в БД
  timeouts:
    total: 2                       # секунд, общий таймаут на запрос
