db:
  path: "bitrix.sqlite"

rate_limit:
  rps: 10

import:
  api_url_template: "https://api.2ip.io/cms/bitrix/ru?page={page}&token={token}"
  token: "o0pi7zyk6tp3bqmh"
  max_domains: 1000000

audit:
  concurrency: 6                    # параллельность
  timeouts:
    total: 10                       # секунд, общий таймаут на запрос
